- .env.example
- pages/api/create-caring-session.js
- pages/index.js
- Changed and cleaned up cause definitions
- Corrected redirects to production domain
> New cause definitions

- pages/HealthWorkshopCard.js
- pages/index.js
I called the API accordingly and created the card.
Please review.
> Added Health workshop card and payment option

- pages/HygieneKitsCard.js
This PR tries to resolve issue #13.
Please Review.
> Added text to hygienekitsCard and price

- pages/HotMealDayCard.js
- pages/HygieneKitsCard.js
- pages/index.js
> Added hot meal day card

- components/HygieneKitsCard.js
- pages/HealthWorkshopCard.js
- pages/HotMealDayCard.js
> removed extra div element

- components/MainDonationForm.js
Updated the donation levels in the main donation form as requested with a $5 and $25 level. Issue #29
> Updated donation levels

- tailwind.config.js
I changed the "md" class width in the tailwind.config.js file to 100% to make the image fill the screen.
> stretch background image to full size

- pages/index.js
this PR works on issue #20.
Please review and suggest changes if needed.
> Sorted cards according to price

- pages/index.js
> Fix deepsource missing key issue

- components/HumanitarianClinicCard.js
- pages/index.js
I have created "HumanitarianClinicCard.js" in components as well as added it into "index.js". Please review and I would be happy to fix any issues. Thank you for the opportunity. This is my first pull  request.
> Create humanitarian clinic card

- .eslintrc.json
- components/FoodDistributionSupportCard.js
- components/HealthWorkshopCard.js
- components/HotMealDayCard.js
- components/HumanitarianClinicCard.js
- components/HygieneKitsCard.js
- components/LaptopForFamiliesCard.js
- components/MainDonationForm.js
- package.json
- pages/_app.js
- pages/_document.js
- pages/api/create-stripe-session.js
- pages/index.js
- pages/thank-you.js
- yarn.lock
Related to #27
Cleaned up the code and added [Eslint](https://eslint.org/).
If you think it is OK then we could think of some code standards. 
Please let me know if [Prettier](https://prettier.io/) integration is needed :)
> Add eslint and fix some deepsource issues

- components/MainDonationForm.js
Improve anyone in need toggle functionality. Previously it disabled the other checkboxes. Now, it will check the other checkboxes & open the option for users to uncheck one or multiple checkboxes. Also, an error handling alert is added which will ask users to check at least one checkbox.
> Improve Anyone In Need & Other Checkbox Functionality

- components/FallPreventionForEldersCard.js
- pages/index.js
Added the fall prevention card and added it to the index page.
> Add fall prevention card

- .gitignore
- components/FoodDistributionSupportCard.js
- components/HealthWorkshopCard.js
- components/HotMealDayCard.js
- components/HumanitarianClinicCard.js
- package.json
- pages/api/create-stripe-session.js
- yarn.lock
Fixed magic numbers detected by the DeepSource analyzer. I'm not sure if there is a code standard on this? Any feedback is appreciated. Issue #27
> fix magic numbers

- pages/thank-you.js
Added a section of social media handles , where people get more to know about  Margarita Humanitarian Foundation and helps making it more recognized and grow in community
>  Added a Reach out Links 

- components/MainDonationForm.js
Removed `mainForm` as it was an unused reference.
Tweaked the `handleSubmit` method to prevent unnecessary loop actions when
`isAnyoneInNeedToggled` is true.
> Main donation form - Fix donate button and clean

- pages/index.js
I agree that removing the image makes for a cleaner look. I want to get this figured out before adding a rings pull request so let me know what you think.
> remove background image and add gradient

- .env.example
- netlify.toml
- pages/api/create-stripe-session.js
- Drop down to one variable for Stripe key: `STRIPE_SECRET_KEY`
- Remove code cruft added to manage differently named environment variable proxies
> Switch to vercel for hosting

- pages/index.js
Center the following with `md:m-auto` this is to align all page content to the center of the screen.
- All page content (except the navbar)
Vertically align centered the following for when the MainDonationForm is expanded.
- Logo
- Description text
- MainDonationForm
> Styling center items

- .eslintrc.json
- components/Footer.js
- components/Navbar.js
> Fix self closing deepsource issues

- components/Footer.js
- components/HeroSection.js
- components/Layout.js
- components/Navbar.js
- pages/_app.js
- pages/fund.js
- pages/give-your-time.js
- pages/in-kind.js
This is proposal for page layout component  and subpages. Should be easier to maintain rather then array of cards.
All comments are welcome 🙂 
Closes #95
> Implement subpages for navbar

- components/PrimaryLayout.js
Changed the title in Components/PrimaryLayout.js .
> title updated to help a family in need #119

- components/MainDonationForm.js
- components/PrimaryLayout.js
Fixed Deepsource identified "Bug risks", this is mostly a set of "best practice" changes, as it is unlikely that these would ever cause a problem when the site is used as expected.
#27
> Fix deepsource bug risks

- pages/give-devices.js
Notes for back end completion:
- Remove `disabled` from the form submit button
- Remove WIP message.
> Add wip message

- .github/ISSUE_TEMPLATE/idea-suggestion.md
Give "IDEA" issues the `idea` label.
#113
> Idea label

- .eslintrc.json
- next.config.js
- package.json
- pages/fund.js
- yarn.lock
Proposal of fully generated page from contentful. Still needs some cleanup but you can get and idea.
All cards data and order is set in contentful.
@audreyfeldroy Please add envs for:
```javascript
space: process.env.CONTENTFUL_SPACE_ID,
accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
```
Common components and structure needs to be cleanup up still but in this way we can move all cards and pages move to contentful.
All proposals are welcome and this is just proof of concept, not the final solution :)
Related to: #125
> Refactor fund cards

- .eslintrc.json
- components/form/InputFormControl.js
- components/form/SelectFormControl.js
- components/form/TextareaFormControl.js
- pages/give-devices.js
I've made a little cleanup of this form with React usage. Should be easier to maintain and add new fields.
> Cleanup give devices form

- pages/give-devices.js
It was done to add stuff from #146 to new form structure.
It:
Closes #146 
Closes #132 
Closes #133 
Closes #134
> Add missing fields to donate form

- Dockerfile
- docker-compose.yml
**Issue #155**
Added two new files at the root level of the project:
`<Dockerfile>` and `<docker-compose.yml>`
The installation can now happen in 2 ways:
1 as it is now (so who's not familiar with Docker can still work on it)
2 using these 2 files, running these 2 commands:
`<docker-compose build>` ===> it builds the docker container (needed only the first time or whenever the container gets removed)
`<docker-compose up>` ===> to run the app inside the container
We may need to edit the CONTRIBUTING.md file.
I find this second approach easier and safer because it isolates the app.
> Dockerize app: added dockerfile and docker-compose

- components/MainDonationForm.js
- components/form/InputFormControl.js
- components/form/SelectFormControl.js
- components/form/TextareaFormControl.js
- pages/give-devices.js
Little change in main donation form to use select component.
> Use select component in main donation form

- CONTRIBUTING.md
> document how to set up the project via Docker

- pages/thank-you.js
Updated the thank you page with latest code.
> updated thank you page

- pages/give-devices.js
> give-devices page: style improvement

- components/Card.js
#176: solve performance issues by removing Tailwind classes responsible for the effect
> removed card hover animation

- components/Navbar.js
- package.json
- yarn.lock
Hey I have removed hardcoded SVGs and replaced it with react-icons one taken from Bootstrap Icons(Search-icon) and Font Awesome (Heart-icon).
Bootstrap Icons : https://react-icons.github.io/react-icons/icons?name=bs
Font Awesome : https://react-icons.github.io/react-icons/icons?name=fa
> Removed hardcoded SVGs and replaced with react-icons

- .github/workflows/format.yml
- .github/workflows/lighthouse.yml
- .gitignore
- lighthouserc.js
This PR sets up Lighthouse Github action to check each PR for performance.
> Add light house action

- components/Card.js
- components/MainDonationForm.js
> Use clsx where needed

- .github/workflows/lighthouse.yml
- lighthouserc.js
The lhci command now works perfectly.
> Fixed lighthouse lhci command not working

- .githooks/notice.md
- .githooks/pre-commit
- README.md
- lint-staged.config.js
- package.json
Closes #163 checking and formatting code before committing
> #163 - Git Hooks

- components/Card.js
> card design made readable

- pages/404.js
- pages/fund.js
Based on Deepsource suggestions:
1) Added Language prop in html in pages/404.html
l
2) Replaced if-else statement with ternary operator in pages/fund.js
> Deepsource: Added Language prop in html and replaced if-else by ternary operator

- components/LandingPageNav.js
- components/LargeHeroSection.js
Fixed [issue](https://deepsource.io/gh/margaritahumanitarian/helpafamily/issue/JS-0424/occurrences?page=1) identified by Deepsource.
#27
> JS-0424: Unnecessary fragments

- components/Astronaut.js
Fixed [issue](https://deepsource.io/gh/margaritahumanitarian/helpafamily/issue/JS-0123/occurrences?page=1) identified by Deepsource.
#27
> JS-0123: Invalid variable declaration

- pages/landing-page.js
Fix issues identified by DeepSource #27
This PR fixes the missing anchor anti-pattern detected by DeepSource [here](https://deepsource.io/gh/margaritahumanitarian/helpafamily/issue/JS-0739/occurrences?page=1)
> JS-0739: Prefer to use anchors in a better way

- README.md
Remove "Our #mhf chat room on Element" from README Resolves #234
> Remove link #234

- components/Footer.js
I noticed the alignment of the Vercel logo and seal in the footer was uneven so I fixed it.
> Fixed alignment of seal in footer

- components/LandingPageNav.js
- components/Navbar.js
- styles/global.css
Replaced some CSS class combinations, used in multiple places by single CSS classes with Tailwind's @apply directive.
Check out #225 for explanation.
> Refactored some CSS classes with Tailwind's @apply

- components/Navbar.js
- components/SideNavbar.js
> Feat: Side navbar for mobile view

- components/ElectronicsDropOffCard.js
Resolves issue #245. I removed the in-line style that was giving the email address a yellow color.
> removed in-line style color yellow on email address

- components/Astronaut.js
- pages/fund.js
This PR fixes the following issues identified by DeepSource:
- [JS-0392](https://deepsource.io/gh/margaritahumanitarian/helpafamily/issue/JS-0392/occurrences?page=1)
- [JS-0240](https://deepsource.io/gh/margaritahumanitarian/helpafamily/issue/JS-0240/occurrences?page=1)
This PR relates to #27 (can't use auto-close keyword since there are still other unfixed issues there).
_Sorry, my branch name has a typo: 0932 should be 0392._
> Fix JS-0392 and JS-0240 identified by DeepSource

- components/LandingPageNav.js
- components/Navbar.js
- components/SideNavbar.js
- models/routes.js
Added link to the logo text.
Additionally, added a small helper module to manage all routes in the project.
It fixes «2» in https://github.com/margaritahumanitarian/helpafamily/issues/250
> ✨ Clickable logo

- README.md
Fixes: #329
* Describe all the points covered in the pull request (changes you might have made)
* Added contributors to the readme file
*(put x in between the brackets to mark them completed [x])*
> Chore: Added contributors to the readme file

- components/Footer.js
I made some small visual adjustments to the footer to give it a little more 💅
> Added padding and separator bar to footer

- components/HeroSection.js
- pages/index.js
This addresses performance issues in #313 where we're getting a hit in performance from using old image formats. Hopefully the Image component fixes this hit.
Also added revalidation so that each day is a new hero image.
> ✨ 🦸 ✨  Hero update with Image component

- components/email/EmailCapture.js
- components/email/SurveySections.js
- package.json
- pages/landing-page.js
- yarn.lock
- Connects to Formspark api
- submits Email and answered questions to formspark
Formspark api uses an env variable called Form_ID 
1. Login to Formspark in MHF account 
2. Click on MFH Email
3. Look for Form id at the top left
4. We need to Create an Env variable in the vercel named FORM_ID.
> Email component backend

- components/Footer.js
We are re-adding the Vercel logo as they are a sponsor of ours.
> Re-added Vercel logo in footer

- pages/index.js
This PR fixes the layout as it was missing the hot meal day section.
*(put x in between the brackets to mark them completed [x])*
> Added the HotMealDaySection component into the home layout

- .github/PULL_REQUEST_TEMPLATE.md
Change helper text to comment.
This will save a few seconds while creating a pull request.
> ⚙️fix: pull request template

- __tests__/components/MainDonationFormInNeed.spec.js
- components/MainDonationForm.js
* includes unit tests
Resolves issue #351 
* this will allow the user to reset form and select specific causes
> Ability to reset form in home page

- components/SideNavbar.js
- More spacing between side-bar links.
- Text animation on hovering.
> Fixes #360

- components/Astronaut/astronaut.spec.js
- components/Card/__mocks__/cardData.js
- components/Card/__snapshots__/card.spec.js.snap
- components/Card/card.spec.js
- components/Card/index.js
- jest.config.js
- yarn.lock
* Coverage should include nested files
* unit tests in Card component
* I need help on the onClick mock function, I can't seem to make it work
> unit test Card component

- components/LargeInfoSection.js
change laptop for family "learn more" link to "https://www.margaritahumanitarian.org/low-income-aid/electronics-for-families".
- [X ] PR title is clear with proper spelling and grammar
- [X ] PR description contains a bulleted list of changes contained in the PR
- [X ] PR links to relevant issues, with keywords to auto-close any issues fully resolved upon merge
- [X ] All automated checks passed
- [ X] Any variables introduced are named clearly and explicitly
> change laptop for family "learn more" link

- package.json
- pages/fund.js
- pages/partner-with-us.js
- yarn.lock
Moved us to Next.js 12.1.0 as well as changed the use of getserversideprops methods to getstaticprops.
> 🆙 🎓 ✨  We're moving to Next 12.1.0
